name: Go CI

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

    - name: Run golangci-lint
      run: golangci-lint run ./...

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check formatting
      run: gofmt -l -s .

  test:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - format

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Extract coverage percentage
      id: coverage
      run: |
        grep -o '^[^:]*' coverage.out | awk '{s+=$1} END {print s/NR}' > coverage.txt
        coverage=$(cat coverage.txt)
        echo "::set-output name=coverage::$coverage"

    - name: Update Shields.io badge
      run: |
        curl -o coverage-badge.svg "https://img.shields.io/badge/Coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen"

    - name: Commit coverage badge
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add coverage-badge.svg
        git commit -m "Update coverage badge"
        git push origin main

  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - format
      - test

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
